moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - slider_controller
    - arm_controller

  slider_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    command_interfaces:
      - position
    joints:
      - slider_to_cart

  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    command_interfaces:
      - position
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
